### ISSUE TITLE
Show number of pages/items available

### ISSUE THREAD

**Issue by tomlankhorst** [developersbolcom/retailer-api#28]
> In general we do not return total counts for resources or the number of pages available; it's up to the user to request subsequent pages until the responses are empty (meaning the end of the list was reached).
[API Release Notes](https://api.bol.com/retailer/public/conventions/index.html)

Add the number of matched items, or the number of pages available, or a 'link' to the next/prev page.

Either as a field in the JSON response or a custom response header. 

Fetching empty pages is not an elegant solution. Especially not since there are strict rate-limits.

**Comment by jwalgemoed** [comment]
Hi @tomlankhorst, while I surely sympathize with your statements, there are a couple of reasons for us to not provide these numbers. Allow me to clarify this:

- The bol.com internal architecture is one made up of microservices. This means we have to aggregate date across several services to create a proper model for our consumers. Most of these services do not provide the requested totals, so we simply do not have them available to share;
- In addition, in most cases, this is by design. Retrieving page counts and total counts requires additional queries to be run against the database for each fetch operation, for optimization's sake it was decided to skip these queries to reduce unnecessary load on our data stores;
- Rate limiting has been configured aggressively to prevent request floods coming from our API users. The stability of the API is always our primary concern, both functionally and technically. If you feel that the current rate limits do not give you enough space to do the requests you need to do, feel free to address this in a ticket. We are still very much in the process of tuning these limits to meet the needs of our users, trying to find a sweet spot between stability and reliability versus usability.

**Comment by jwalgemoed** [comment]
@tomlankhorst I will update the documentation on paging to include the considerations that lead us to this implementation.

**Comment by tomlankhorst** [comment]
Very well, I am however not completely satisfied 😌. 

> Retrieving page counts and total counts requires additional queries to be run against the database for each fetch operation, for optimization's sake it was decided to skip these queries to reduce unnecessary load on our data stores'

While on the other hand the documentation suggests: 
> it's up to the user to request subsequent pages until the responses are empty (meaning the end of the list was reached).

Which not only effectively moves the problem, but now also burdens the client with this extra request. 

So, I feel like there are two options: 

- Either expose the number of pages available / a link to the following page
- OR Make the number of items per page `M` **explicit** in the documentation such that checking whether a result count `N` to equal `M` indicates that there _might_ be another results page.

**Comment by jwalgemoed** [comment]
Hi @tomlankhorst, thank you for taking the time to respond. Allow me to respond:

> While on the other hand the documentation suggests:
> 
> it's up to the user to request subsequent pages until the responses are empty (meaning the end of the list was reached).

This is very much true, and is the reason why I wanted to amend this documentation, as it does not provide all the details. I will make some changes soon to properly highlight our choices and the effects they may have on our users.

> Either expose the number of pages available / a link to the following page
> OR Make the number of items per page M explicit in the documentation such that checking whether a result count N to equal M indicates that there might be another results page.

Bot are great options, but as I mentioned before, the first one isn't an option for us at this time. Adding a link is a possibility, in situations where we know due to page size that we are on the last page, but this is not planned at this time.

The second option is what we thought of ourselves too, which is why we have already implemented it some time ago. In the redoc documentation (For example for the orders list call https://api.bol.com/retailer/public/redoc/v3#tag/Orders) we have added context to all page parameters (for example in the aforementioned open orders case):

> The page to get with max 50 results per page.

While this copy can be improved, I see that now :) we stipulate that pages are 50 items large. If I interpreted your comments correctly, that should be sufficient for you to know if you'd need to do an extra request. At the time of writing this, the current number of items per page is a fixed 50 items for all endpoints returning lists. This may change however, so it's always good to check the redoc for explicit numbers.
