### ISSUE TITLE
Provide detailled order information at /retailer/orders

### ISSUE THREAD

**Issue by tomlankhorst** [developersbolcom/retailer-api#29]
The `/retailer/orders` endpoint provides very limited information about orders. 
Detailed information is only available in the endpoint for specific orders `/retailer/orders/xxxxxx`. 

The very low rate limits make this impractical. 
Please add detailed information (addresses, product fees) to the `/retailer/orders` endpoint.

**Comment by jwalgemoed** [comment]
Hi @tomlankhorst, let me begin by saying that this was a conscious choice. Our internal landscape is one of microservices, which forces us to aggregate detailed models of orders over several interconnected services. This is a time consuming and expensive operation, and one you'd not want to do particularly when it comes to resources returning lists.

In addition, before the choice was made, we reached out to a subset of our connected API users to find out how this order list was used in the first place. The feedback we received was that it was used mainly as a trigger to register new orders coming in, and that the single (`/retailer/orders/xxx`) was called when fulfilment of the order was taking place. In most cases the full order info wasn't needed every time the request to `/retailer/orders` was made; causing us to redundantly aggregate lot's of information for nothing. Another side-effect of this was that we were continuously resending complete order models of older orders that were still in the list due to not being shipped yet. We've tested this choice during a closed beta in March, and have found that the general consensus was that this was working well for our users. 

So, when looking at the usage patterns for the endpoints, we were able to get to a win-win situation, where we provide _just enough_ information in the list call to allow business processes to continue for our API users. They then can call the single order endpoint to get a more expansive model of the so they can take action on it.

I hope this explains the reasoning behind the endpoints created in the v3 retailer API. One more comment regarding your last question (and the somewhat related issue here https://github.com/developersbolcom/developersbolcom.github.io/issues/28): It feels like the underlying issue is the aggressive rate limits. Like I mentioned in the linked issue, we are definitely open to have a discussion on what limits would work for you. In the end, it's all about stability but that doesn't mean there's no room to move.

**Comment by tomlankhorst** [comment]
Very well, in that case, I suppose an appropriate rate-limit would be:

`rate-limit( all orders endpoint ) x page-size( all orders endpoint ) `

So, that would boil down to...

`7 requests / 3 minutes * 20 orders = 45 requests per minute. `

Such that, when using efficiently, you could at least obtain all order information.

**Comment by jwalgemoed** [comment]
@tomlankhorst I agree. We will update the rate limits to give you some more slack. As I pointed out in the other ticket you made, we return 50 orders per page, so we will update the rate limits to allow for this. We are currently making some other changes in this area as well, so I can't yet confirm when this will be released, but it should be soon.
