### ISSUE TITLE
Synchronous and async

### ISSUE THREAD

**Issue by nopfinance** [developersbolcom/retailer-api#56]
When we moved from the API2 to API3 we had to implement the more robust and scalable asynchronous queue mechanism.

Looking at offer insight and sales prediction it seems that these two end points are designed to be synchronous services, thereby leaving the async route. There is a big chance that in the future you will have to redesign this into async too, thereby generating work for integrators as well.

Therefore I'd prefer a async mechanism using process status responses just like we have on offers, orders, shipments etc etc

**Comment by koenmolkenboer** [comment]
Thanks for the suggestion. I discussed it with my colleagues, but we will use synchronous calls for the offer insight and sales prediction. Only for the POST/PUT/DELETE calls we will use the asynchronous queue mechanism.

**Comment by gvantuijl** [comment]
Hi @nopfinance 
Thanks for your feedback! Let me clarify this for you a bit.

Our GET calls are always synchronous in comparison to our POST/PUT/DELETE requests, as you can read on [our convention page](https://api.bol.com/retailer/public/conventions/index.html). The reason we apply this logic is because of the load that is coming in over the course of the day. Any POST/PUT/DELETE request is put onto a queue first and send to our downstream systems when next in line. Depending on the traffic at that moment in time, it might take (much) longer to receive a response back. This logic would then also apply for a GET response.

If everything would be asynchronously there would be no way to fetch data instantly from bol.com. And by the time you would get the response back, the world might have already changed again and the response has become outdated. You should question if this would actually work for you. For now, this was a deliberate choice and not likely to change in the near feature.
